
# Configuração do Supabase para a função edge quiz-webhook
project_id = "nmxfknwkhnengqqjtwru"

[api]
# Configurações da API

[db]
# Configurações do banco de dados

[studio]
# Configurações do Studio

[functions]
[functions.quiz-webhook]
verify_jwt = false
