/**
 * Dados das perguntas do questionário MAR
 */
export const quizQuestionsData = [
  {
    order_number: 1,
    text: "Qual o seu nome completo?",
    type: "text",
    required: true,
    hint: "Digite seu nome completo",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 2,
    text: "Qual o seu cargo na empresa?",
    type: "text",
    required: true,
    hint: "Digite seu cargo na empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 3,
    text: "Qual o nome da sua empresa?",
    type: "text",
    required: true,
    hint: "Digite o nome da sua empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 4,
    text: "Qual o seu e-mail de contato?",
    type: "text",
    required: true,
    hint: "Digite seu e-mail de contato",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 5,
    text: "Qual o seu telefone de contato?",
    type: "text",
    required: true,
    hint: "Digite seu telefone de contato",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 6,
    text: "Qual o segmento da sua empresa?",
    type: "text",
    required: true,
    hint: "Digite o segmento da sua empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 7,
    text: "Quantos funcionários sua empresa possui?",
    type: "radio",
    required: true,
    hint: "Selecione o número de funcionários da sua empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 8,
    text: "Qual o faturamento anual da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione o faturamento anual da sua empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 9,
    text: "Como você descreveria o seu conhecimento sobre marketing?",
    type: "radio",
    required: true,
    hint: "Selecione o nível de conhecimento que melhor descreve sua experiência com marketing",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 10,
    text: "Qual o principal objetivo de marketing da sua empresa atualmente?",
    type: "radio",
    required: true,
    hint: "Selecione o objetivo que sua empresa busca alcançar com o marketing",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 11,
    text: "Quais canais de marketing sua empresa utiliza com mais frequência?",
    type: "checkbox",
    required: true,
    hint: "Selecione os canais de marketing que sua empresa utiliza com mais frequência",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 12,
    text: "Qual o seu orçamento mensal para marketing?",
    type: "radio",
    required: true,
    hint: "Selecione a faixa de orçamento que sua empresa investe em marketing mensalmente",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 13,
    text: "Como você avalia o retorno sobre o investimento (ROI) das suas ações de marketing?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve como você avalia o ROI das suas ações de marketing",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 14,
    text: "Quais métricas você acompanha para medir o sucesso das suas campanhas de marketing?",
    type: "checkbox",
    required: true,
    hint: "Selecione as métricas que você acompanha para medir o sucesso das suas campanhas de marketing",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 15,
    text: "Qual a sua principal dificuldade em relação ao marketing da sua empresa?",
    type: "textarea",
    required: true,
    hint: "Descreva qual a sua principal dificuldade em relação ao marketing da sua empresa",
    module_id: "e4b1b111-9c9a-4b5a-8b0e-7b7b7b7b7b7b",
  },
  {
    order_number: 16,
    text: "Como você descreveria o seu processo de vendas atual?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve o seu processo de vendas atual",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 17,
    text: "Qual o tamanho da sua equipe de vendas?",
    type: "radio",
    required: true,
    hint: "Selecione o tamanho da sua equipe de vendas",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 18,
    text: "Qual o ticket médio de vendas da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione o ticket médio de vendas da sua empresa",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 19,
    text: "Qual o tempo médio de fechamento de uma venda?",
    type: "radio",
    required: true,
    hint: "Selecione o tempo médio de fechamento de uma venda",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 20,
    text: "Quais as principais fontes de leads da sua empresa?",
    type: "checkbox",
    required: true,
    hint: "Selecione as principais fontes de leads da sua empresa",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 21,
    text: "Qual a taxa de conversão de leads em clientes?",
    type: "radio",
    required: true,
    hint: "Selecione a taxa de conversão de leads em clientes",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 22,
    text: "Qual a sua principal dificuldade em relação às vendas da sua empresa?",
    type: "textarea",
    required: true,
    hint: "Descreva qual a sua principal dificuldade em relação às vendas da sua empresa",
    module_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  },
  {
    order_number: 23,
    text: "Como você descreveria a saúde financeira da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve a saúde financeira da sua empresa",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 24,
    text: "Qual o regime tributário da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione o regime tributário da sua empresa",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 25,
    text: "Sua empresa possui um sistema de gestão financeira?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa possui um sistema de gestão financeira",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 26,
    text: "Com que frequência você acompanha o fluxo de caixa da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione a frequência com que você acompanha o fluxo de caixa da sua empresa",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 27,
    text: "Sua empresa possui um planejamento financeiro?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa possui um planejamento financeiro",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 28,
    text: "Qual a sua principal dificuldade em relação às finanças da sua empresa?",
    type: "textarea",
    required: true,
    hint: "Descreva qual a sua principal dificuldade em relação às finanças da sua empresa",
    module_id: "b8a9d123-4567-890a-bcde-f01234567890",
  },
  {
    order_number: 29,
    text: "Como você descreveria a eficiência dos processos operacionais da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve a eficiência dos processos operacionais da sua empresa",
    module_id: "c5d6e7f8-90ab-cdef-1234-567890abcdef",
  },
  {
    order_number: 30,
    text: "Sua empresa utiliza alguma ferramenta de gestão de projetos?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa utiliza alguma ferramenta de gestão de projetos",
    module_id: "c5d6e7f8-90ab-cdef-1234-567890abcdef",
  },
  {
    order_number: 31,
    text: "Sua empresa possui um sistema de controle de qualidade?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa possui um sistema de controle de qualidade",
    module_id: "c5d6e7f8-90ab-cdef-1234-567890abcdef",
  },
  {
    order_number: 32,
    text: "Como você avalia a capacidade da sua empresa de se adaptar a mudanças no mercado?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve a capacidade da sua empresa de se adaptar a mudanças no mercado",
    module_id: "c5d6e7f8-90ab-cdef-1234-567890abcdef",
  },
  {
    order_number: 33,
    text: "Qual a sua principal dificuldade em relação aos processos operacionais da sua empresa?",
    type: "textarea",
    required: true,
    hint: "Descreva qual a sua principal dificuldade em relação aos processos operacionais da sua empresa",
    module_id: "c5d6e7f8-90ab-cdef-1234-567890abcdef",
  },
  {
    order_number: 34,
    text: "Como você descreveria o clima organizacional da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve o clima organizacional da sua empresa",
    module_id: "d2e3f4g5-6789-0abc-def1-23456789abcd",
  },
  {
    order_number: 35,
    text: "Sua empresa possui um plano de carreira para os funcionários?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa possui um plano de carreira para os funcionários",
    module_id: "d2e3f4g5-6789-0abc-def1-23456789abcd",
  },
  {
    order_number: 36,
    text: "Sua empresa oferece treinamentos para os funcionários?",
    type: "radio",
    required: true,
    hint: "Selecione se sua empresa oferece treinamentos para os funcionários",
    module_id: "d2e3f4g5-6789-0abc-def1-23456789abcd",
  },
  {
    order_number: 37,
    text: "Como você avalia o nível de engajamento dos seus funcionários?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve o nível de engajamento dos seus funcionários",
    module_id: "d2e3f4g5-6789-0abc-def1-23456789abcd",
  },
  {
    order_number: 38,
    text: "Qual a sua principal dificuldade em relação à gestão de pessoas na sua empresa?",
    type: "textarea",
    required: true,
    hint: "Descreva qual a sua principal dificuldade em relação à gestão de pessoas na sua empresa",
    module_id: "d2e3f4g5-6789-0abc-def1-23456789abcd",
  },
  {
    order_number: 39,
    text: "Qual o seu nível de satisfação com os resultados da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione o nível de satisfação que melhor descreve sua experiência com os resultados da sua empresa",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 40,
    text: "Quais as suas principais metas para os próximos 12 meses?",
    type: "textarea",
    required: true,
    hint: "Descreva quais as suas principais metas para os próximos 12 meses",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 41,
    text: "Quais os seus maiores desafios para alcançar essas metas?",
    type: "textarea",
    required: true,
    hint: "Descreva quais os seus maiores desafios para alcançar essas metas",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 42,
    text: "O que você espera alcançar com a consultoria da Crie Valor?",
    type: "textarea",
    required: true,
    hint: "Descreva o que você espera alcançar com a consultoria da Crie Valor",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 43,
    text: "Como você conheceu a Crie Valor?",
    type: "radio",
    required: true,
    hint: "Selecione como você conheceu a Crie Valor",
    module_id: "f36c994b-cb94-497a-b49b-a94990195a5b",
  },
  {
    order_number: 44,
    text: "Qual a sua expectativa de crescimento da receita (faturamento) da sua empresa para os próximos 12 meses?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor representa suas expectativas de crescimento",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 45,
    text: "Quais são as suas principais metas financeiras para os próximos 12 meses?",
    type: "checkbox",
    required: true,
    hint: "Você pode marcar mais de uma opção",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 46,
    text: "Sua empresa possui um planejamento financeiro (orçamento) para os próximos 12 meses?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve o planejamento financeiro da sua empresa",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 47,
    text: "Quais indicadores financeiros você acompanha para saber como está a saúde financeira da sua empresa?",
    type: "checkbox",
    required: true,
    hint: "Você pode marcar mais de uma opção",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 48,
    text: "Sua empresa planeja fazer algum investimento importante (em equipamentos, tecnologia, reformas, etc.) nos próximos 12 meses? Se sim, qual o valor aproximado?",
    type: "radio",
    required: true,
    hint: "Selecione a faixa de investimento planejada",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 49,
    text: "Como você avalia a situação financeira atual da sua empresa?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve a situação financeira atual da sua empresa",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  {
    order_number: 50,
    text: "Pensando na parte financeira da sua empresa, qual é a sua maior prioridade ou o problema mais urgente que precisa ser resolvido nos próximos 12 meses?",
    type: "textarea",
    required: true,
    hint: "Descreva detalhadamente sua prioridade ou problema financeiro mais urgente",
    module_id: "e3f4g5h6-7890-abcd-ef12-3456789abcde",
  },
  
  // Módulo 8: Perspectiva de Processos Internos
  {
    order_number: 51,
    text: "Quais são os três processos mais importantes para que sua empresa alcance seus objetivos nos próximos 12 meses?",
    type: "textarea",
    required: true,
    hint: "Liste os processos mais importantes (exemplos: processo de vendas, produção, atendimento ao cliente, etc.)",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 52,
    text: "Sua empresa utiliza alguma forma de organizar e melhorar seus processos de trabalho?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve como sua empresa organiza seus processos",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 53,
    text: "Como você verifica se os processos da sua empresa estão funcionando bem?",
    type: "checkbox",
    required: true,
    hint: "Marque todas as opções que se aplicam",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 54,
    text: "Sua empresa pretende fazer alguma mudança importante ou criar algo novo nos seus processos de trabalho nos próximos 12 meses? Se sim, o quê?",
    type: "textarea",
    required: true,
    hint: "Descreva as mudanças planejadas para os processos de trabalho",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 55,
    text: "Como sua empresa garante a qualidade dos produtos ou serviços que oferece?",
    type: "textarea",
    required: true,
    hint: "Descreva os procedimentos de garantia de qualidade da sua empresa",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 56,
    text: "Sua empresa utiliza alguma ferramenta ou sistema para ajudar a gerenciar os processos internos?",
    type: "radio",
    required: true,
    hint: "Selecione a opção que melhor descreve as ferramentas utilizadas",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  },
  {
    order_number: 57,
    text: "Pensando nos processos internos da sua empresa, qual é a sua maior prioridade ou o problema mais urgente que precisa ser resolvido nos próximos 12 meses?",
    type: "textarea",
    required: true,
    hint: "Descreva detalhadamente sua prioridade ou problema relacionado aos processos internos",
    module_id: "f4g5h6i7-8901-bcde-f123-456789abcdef",
  }
];
